# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'shareba_business' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shareba_business
  pod 'SnapKit'
  pod 'FDTemplateLayoutCell'
  pod 'SwiftyJSON'
  pod 'ESTabBarController-swift'
  pod 'AMScrollingNavbar'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'ObjectMapper'
#建立Pod參考這個的 https://www.jianshu.com/p/46df9d2cbac9
end
